### ISSUE TITLE
支持的平台

### ISSUE THREAD

**Issue by GWan1234** [doushang/luci-app-shortcutmenu#1]
感谢山友的开发工作！
有一个疑惑，请问这个插件能支持其他平台吗？比如arm架构设备，x86下没问题我刚刚试了。

**Comment by doushang** [comment]
理论上应该是可以的，这个插件只是几行前端代码。

**Comment by GWan1234** [comment]
> 理论上应该是可以的，这个插件只是几行前端代码。

get，多谢🙏
